# -*- coding: utf-8 -*-
"""01_opencv-basics_yolo-detection.ipynb

Automatically generated by Colab.

"""

pip install ultralytics

import cv2
import numpy as np
from ultralytics import YOLO
from google.colab.patches import cv2_imshow

from google.colab import drive
drive.mount('/content/drive')

img_path = '/content/drive/MyDrive/Colab_Notebooks/Images/Image-1.png'

img = cv2.imread(img_path)

gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

cv2_imshow(gray_img)

blurred_img = cv2.GaussianBlur(gray_img, (5, 5), 0)

cv2_imshow(blurred_img)

edges = cv2.Canny(blurred_img, 50, 150)

cv2_imshow(edges)

resized_img = cv2.resize(edges, (400, 400))

cv2_imshow(resized_img)

(h, w) = img.shape[:2]
center = (w // 2, h // 2)
matrix = cv2.getRotationMatrix2D(center, 45, 1.0)
rotated_img = cv2.warpAffine(resized_img, matrix, (w, h))
cv2_imshow(rotated_img)

model = YOLO('yolov8n.pt')
results = model(img)
annotated_img = results[0].plot()
cv2_imshow(annotated_img)