# -*- coding: utf-8 -*-
"""03_mnist_from-scratch_numpy_and_keras.ipynb

Automatically generated by Colab.

"""

pip install tensorflow

pip install mnist

import numpy as np
import matplotlib.pyplot as plt
import cv2
import tensorflow as tf
from tensorflow.keras.datasets import mnist
from sklearn.model_selection import train_test_split

print("1. Loading the MNIST dataset...")
(X_train_full, y_train_full), (X_test, y_test) = mnist.load_data()

X_train, X_val, y_train, y_val = train_test_split(
    X_train_full, y_train_full, test_size=0.2, random_state=42
)

X_train_n = X_train.astype("float32") / 255.0
X_val_n = X_val.astype("float32") / 255.0
X_test_n = X_test.astype("float32") / 255.0

from tensorflow.keras.utils import to_categorical
y_train_oh = to_categorical(y_train, 10)
y_val_oh = to_categorical(y_val, 10)
y_test_oh = to_categorical(y_test, 10)

X_train_n = np.expand_dims(X_train_n, axis=-1)
X_val_n = np.expand_dims(X_val_n, axis=-1)
X_test_n = np.expand_dims(X_test_n, axis=-1)

from tensorflow.keras.preprocessing.image import ImageDataGenerator
import numpy as np

datagen = ImageDataGenerator(
    rotation_range=15,
    width_shift_range=0.1,
    height_shift_range=0.1,
    zoom_range=0.1,
    fill_mode='nearest'
)

sample_img = X_train_n[0:1]
aug_iter = datagen.flow(sample_img, batch_size=1)

plt.figure(figsize=(10, 3))
for i in range(10):
  plt.subplot(1, 10, i + 1)
  batch = next(aug_iter)
  plt.imshow(batch[0].squeeze(), cmap='gray')
  plt.title(f"Aug {i+1}")
  plt.axis('off')
plt.show()

def sigmoid(x):
  return 1 / (1 + np.exp(-x))

def sigmoid_der(x):
  return x * (1 - x)

X_example = X_train_n[0].flatten().reshape(1, 784)
y_example = y_train_oh[0].reshape(1, 10)

weights = np.random.randn(784, 10) * 0.01
bias = np.zeros((1, 10))

z = np.dot(X_example, weights) + bias
output = sigmoid(z)

error = y_example - output
loss = np.mean(np.square(error))

d_output = error * sigmoid_der(output)
weights += np.dot(X_example.T, d_output) * 0.1

print(f"\nNumPy Example - Loss: {loss:.4f}")

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Input

model = Sequential([
    Input(shape=(28, 28, 1)),
    Flatten(),
    Dense(128, activation='relu'),
    Dense(10, activation='softmax')
])

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.summary()

history = model.fit(
    X_train_n, y_train_oh,
    batch_size = 64,
    validation_data=(X_val_n, y_val_oh),
    epochs=5
)