# -*- coding: utf-8 -*-
"""04_mnist_neural-network_training.ipynb

Automatically generated by Colab.

"""

import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
from tensorflow.keras.datasets import mnist
from sklearn.model_selection import train_test_split

(X_train_full, y_train_full), (X_test, y_test) = mnist.load_data()
X_train, X_val, y_train, y_val = train_test_split(X_train_full, y_train_full)

X_train_n = X_train.astype("float32") / 255.0
X_val_n = X_val.astype("float32") / 255.0
X_test_n = X_test.astype("float32") / 255.0

X_train = X_train_n
X_val = X_val_n
X_test = X_test_n

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Dropout
from tensorflow.keras import layers, models, optimizers

model = models.Sequential([
    layers.Flatten(input_shape=(28, 28, 1)),
    layers.Dense(128, activation="relu"),
    layers.Dropout(0.2),
    layers.Dense(64, activation="sigmoid"),
    layers.Dropout(0.5),
    layers.Dense(10, activation="softmax")
])

model.summary()

model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

def scheduler(epoch, lr):
  if epoch < 3:
    return lr
  else:
    return lr * 0.5

lr_callback = tf.keras.callbacks.LearningRateScheduler(scheduler)

history = model.fit(
    X_train, y_train,
    epochs=10,
    batch_size=64,
    validation_split=0.1,
    callbacks=[lr_callback],
    verbose=1
)

test_loss, test_acc = model.evaluate(X_test, y_test, verbose=1)
print(f"\nTest Set Accuracy: {test_acc*100:.2f}%")

model = models.Sequential([
    layers.Flatten(input_shape=(28, 28, 1)),
    layers.Dense(128, activation="relu"),
    layers.Dropout(0.01),
    layers.Dense(64, activation="sigmoid"),
    layers.Dropout(0.01),
    layers.Dense(64, activation="relu"),
    layers.Dropout(0.01),
    layers.Dense(10, activation="softmax")
])

model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

history = model.fit(
    X_train, y_train,
    epochs=20,
    batch_size=64,
    validation_split=0.1,
    callbacks=[lr_callback],
    verbose=1
)

test_loss, test_acc = model.evaluate(X_test, y_test, verbose=1)
print(f"\nTest Set Accuracy: {test_acc*100:.2f}%")
